### PR TITLE
Adding web node

### PR DESCRIPTION
**Pull request by arshul**

### CODE REVIEW

**Comment by arshul** [comment]
> So by default, the web node get the login node attribute if web_node is true, but we can still set the value for web instance. If that is the case, then I like it.

No, you can't pass a value for `web` in the `instances` variable as of now.
 
If we define an object variable with `web` as a key, then we have to pass it every time.

A possible solution for that usecase could be something like:
```instances = {
    mgmt  = { type = "p4-6gb", count = 1 },
    login = { type = "p2-3gb", count = 1 },
    web = { type = "p2-3gb", count =  0},
    node  = 
      { type = "p2-3gb", count = 1 },
    ]
}```

send the web node count as 0 if the node is not needed, but omitting the `web` key would cause the script to break.

**Comment by poquirion** [comment]
I get the following error:

```
Error: Your query returned no results. Please change your search criteria and try again.

  on ../magic_castle/openstack/infrastructure.tf line 8, in data "openstack_compute_flavor_v2" "mgmt":
   8: data "openstack_compute_flavor_v2" "mgmt" {
```
here is my main.tf:
```
terraform {
  required_version = ">= 0.12.21"
}

module "openstack" {
  # source = "git::https://github.com/c3g/magic_castle.git//openstack"
  source = "../magic_castle//openstack"

  cluster_name = "phoenix"
  domain       = "calculquebec.cloud"
  image        = "CentOS-7-x64-2019-07"
  nb_users     = 10
  puppetenv_git= "https://github.com/c3g/puppet-magic_castle"
  puppetenv_rev = "web_node"

  instances = {
    mgmt  = { type = "p4-6gb", count = 1 },
    login = { type = "p2-3gb", count = 1 },
    node  = [
      { type = "p2-3gb", count = 1 },
    ]
  }
  web_node = true

  storage = {
    type         = "nfs"
    home_size    = 100
    project_size = 50
    scratch_size = 50
  }

  public_keys = [file("~/.ssh/id_rsa.pub")]

  # Shared password, randomly chosen if blank
  guest_passwd = ""

  # OpenStack specific
  os_floating_ips = []
}

output "sudoer_username" {
  value = module.openstack.sudoer_username
}

output "guest_usernames" {
  value = module.openstack.guest_usernames
}

output "guest_passwd" {
  value = module.openstack.guest_passwd
}

output "public_ip" {
  value = module.openstack.ip
}
```

**Comment by poquirion** [comment]
> > So by default, the web node get the login node attribute if web_node is true, but we can still set the value for web instance. If that is the case, then I like it.
> 
> No, you can't pass a value for `web` in the `instances` variable as of now.
> 
> If we define an object variable with `web` as a key, then we have to pass it every time.
> 
> A possible solution for that usecase could be something like:
> 
> ```
> instances = {
>     mgmt  = { type = "p4-6gb", count = 1 },
>     login = { type = "p2-3gb", count = 1 },
>     web = { type = "p2-3gb", count =  0},
>     node  = 
>       { type = "p2-3gb", count = 1 },
>     ]
> }
> ```
> 
> send the web node count as 0 if the node is not needed, but omitting the `web` key would cause the script to break.

I see, lets use the same flavor ad login then.

**Comment by poquirion** [comment]
```
Error: Your query returned no results. Please change your search criteria and try again.

  on ../magic_castle/openstack/infrastructure.tf line 8, in data "openstack_compute_flavor_v2" "mgmt":
   8: data "openstack_compute_flavor_v2" "mgmt" {
```
ok, got it.  "p4-6gb" flavor is not available in the project....

**Comment by poquirion** [comment]
Ok back at it agaIn. Here is what I would do for the web node:
```
variable "instances" {
  type = object({
    mgmt=object({type=string, count=number}),
    login=object({type=string, count=number}),
    node=list(map(any)),
  })
  description = "Map that defines the parameters for each type of instance of the cluster"
}

variable  "web_instance" {
  type        = object({type=string, count=number})
  default     = { type = "",  count =  0},
  description = "Set type and count > 0, to add an additional node with web feature."
}

```
 you can convert a number into bool, here is a reference I have found for that: https://github.com/hashicorp/terraform/issues/23741#issuecomment-568141903

**Comment by arshul** [comment]
> Ok back at it agaIn. Here is what I would do for the web node:
> 
> ```
> variable "instances" {
>   type = object({
>     mgmt=object({type=string, count=number}),
>     login=object({type=string, count=number}),
>     node=list(map(any)),
>   })
>   description = "Map that defines the parameters for each type of instance of the cluster"
> }
> 
> variable  "web_instance" {
>   type        = object({type=string, count=number})
>   default     = { type = "",  count =  0},
>   description = "Set type and count > 0, to add an additional node with web feature."
> }
> ```
> 
> you can convert a number into bool, here is a reference I have found for that: [hashicorp/terraform#23741 (comment)](https://github.com/hashicorp/terraform/issues/23741#issuecomment-568141903)

Perfect!! I'll update the PR with this change.

**Pull request closed without merging**
